//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------

#include "nanoFramework_Camera.h"

// clang-format off

static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_nanoFramework_Camera_nanoFramework_Camera_Camera::NativeInit___STATIC__I4__I4__I4__I4__I4__I4__I4__I4__I4__I4__I4__I4__I4__I4__I4__I4__I4__I4__I4__I4__I4,
    Library_nanoFramework_Camera_nanoFramework_Camera_Camera::NativeGetJpeg___STATIC__SZARRAY_U1,
    Library_nanoFramework_Camera_nanoFramework_Camera_Camera::NativeDeinit___STATIC__VOID,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_nanoFramework_Camera =
{
    "nanoFramework.Camera",
    0x85DA61A2,
    method_lookup,
    { 1, 0, 0, 0 }
};

// clang-format on
