//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------

#include "nanoFramework_Camera.h"
#include "nanoFramework_Camera_nanoFramework_Camera_Camera.h"

#include <cstring>
#include <esp_camera.h>

using namespace nanoFramework_Camera::nanoFramework_Camera;


HRESULT Library_nanoFramework_Camera_nanoFramework_Camera_Camera::NativeInit___STATIC__I4__I4__I4__I4__I4__I4__I4__I4__I4__I4__I4__I4__I4__I4__I4__I4__I4__I4__I4__I4__I4( CLR_RT_StackFrame& stack )
{
    NANOCLR_HEADER(); hr = S_OK;
    {

        signed int param0;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_INT32( stack, 0, param0 ) );

        signed int param1;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_INT32( stack, 1, param1 ) );

        signed int param2;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_INT32( stack, 2, param2 ) );

        signed int param3;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_INT32( stack, 3, param3 ) );

        signed int param4;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_INT32( stack, 4, param4 ) );

        signed int param5;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_INT32( stack, 5, param5 ) );

        signed int param6;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_INT32( stack, 6, param6 ) );

        signed int param7;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_INT32( stack, 7, param7 ) );

        signed int param8;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_INT32( stack, 8, param8 ) );

        signed int param9;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_INT32( stack, 9, param9 ) );

        signed int param10;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_INT32( stack, 10, param10 ) );

        signed int param11;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_INT32( stack, 11, param11 ) );

        signed int param12;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_INT32( stack, 12, param12 ) );

        signed int param13;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_INT32( stack, 13, param13 ) );

        signed int param14;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_INT32( stack, 14, param14 ) );

        signed int param15;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_INT32( stack, 15, param15 ) );

        signed int param16;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_INT32( stack, 16, param16 ) );

        signed int param17;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_INT32( stack, 17, param17 ) );

        signed int param18;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_INT32( stack, 18, param18 ) );

        signed int param19;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_INT32( stack, 19, param19 ) );

        signed int retValue = Camera::NativeInit( param0, param1, param2, param3, param4, param5, param6, param7, param8, param9, param10, param11, param12, param13, param14, param15, param16, param17, param18, param19, hr );
        NANOCLR_CHECK_HRESULT( hr );
        SetResult_INT32( stack, retValue );
    }
    NANOCLR_NOCLEANUP();
}

HRESULT Library_nanoFramework_Camera_nanoFramework_Camera_Camera::NativeGetJpeg___STATIC__SZARRAY_U1( CLR_RT_StackFrame& stack )
{
    NANOCLR_HEADER(); hr = S_OK;
    {
        camera_fb_t *frame = esp_camera_fb_get();
        if (frame == nullptr)
        {
            NANOCLR_SET_AND_LEAVE(CLR_E_FAIL);
        }

        CLR_RT_HeapBlock_Array *jpeg = nullptr;
        hr = CLR_RT_HeapBlock_Array::CreateInstance(jpeg, frame->len, g_CLR_RT_WellKnownTypes.m_UInt8);

        if (SUCCEEDED(hr))
        {
            memcpy(jpeg->GetFirstElement(), frame->buf, frame->len);
            stack.SetResult_Object(jpeg);
        }

        esp_camera_fb_return(frame);
        NANOCLR_CHECK_HRESULT(hr);
    }
    NANOCLR_NOCLEANUP();
}

HRESULT Library_nanoFramework_Camera_nanoFramework_Camera_Camera::NativeDeinit___STATIC__VOID( CLR_RT_StackFrame& stack )
{
    NANOCLR_HEADER(); hr = S_OK;
    {

        Camera::NativeDeinit(  hr );
        NANOCLR_CHECK_HRESULT( hr );

    }
    NANOCLR_NOCLEANUP();
}
