//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------

#ifndef NANOFRAMEWORK_CAMERA_H
#define NANOFRAMEWORK_CAMERA_H

#include <nanoCLR_Interop.h>
#include <nanoCLR_Runtime.h>
#include <nanoPackStruct.h>

typedef enum __nfpack CameraFrameSize
{
    CameraFrameSize_Qqvga = 0,
    CameraFrameSize_Qvga = 1,
    CameraFrameSize_Vga = 2,
    CameraFrameSize_Svga = 3,
    CameraFrameSize_Xga = 4,
    CameraFrameSize_Sxga = 5,
    CameraFrameSize_Uxga = 6,
} CameraFrameSize;

struct Library_nanoFramework_Camera_nanoFramework_Camera_CameraConfiguration
{
    // renamed backing field '<PinPowerDown>k__BackingField'
    static const int FIELD__PinPowerDown = 1;
    // renamed backing field '<PinReset>k__BackingField'
    static const int FIELD__PinReset = 2;
    // renamed backing field '<PinXclk>k__BackingField'
    static const int FIELD__PinXclk = 3;
    // renamed backing field '<PinSiod>k__BackingField'
    static const int FIELD__PinSiod = 4;
    // renamed backing field '<PinSioc>k__BackingField'
    static const int FIELD__PinSioc = 5;
    // renamed backing field '<PinD7>k__BackingField'
    static const int FIELD__PinD7 = 6;
    // renamed backing field '<PinD6>k__BackingField'
    static const int FIELD__PinD6 = 7;
    // renamed backing field '<PinD5>k__BackingField'
    static const int FIELD__PinD5 = 8;
    // renamed backing field '<PinD4>k__BackingField'
    static const int FIELD__PinD4 = 9;
    // renamed backing field '<PinD3>k__BackingField'
    static const int FIELD__PinD3 = 10;
    // renamed backing field '<PinD2>k__BackingField'
    static const int FIELD__PinD2 = 11;
    // renamed backing field '<PinD1>k__BackingField'
    static const int FIELD__PinD1 = 12;
    // renamed backing field '<PinD0>k__BackingField'
    static const int FIELD__PinD0 = 13;
    // renamed backing field '<PinVsync>k__BackingField'
    static const int FIELD__PinVsync = 14;
    // renamed backing field '<PinHref>k__BackingField'
    static const int FIELD__PinHref = 15;
    // renamed backing field '<PinPclk>k__BackingField'
    static const int FIELD__PinPclk = 16;
    // renamed backing field '<XclkFrequencyHz>k__BackingField'
    static const int FIELD__XclkFrequencyHz = 17;
    // renamed backing field '<FrameSize>k__BackingField'
    static const int FIELD__FrameSize = 18;
    // renamed backing field '<JpegQuality>k__BackingField'
    static const int FIELD__JpegQuality = 19;
    // renamed backing field '<FrameBufferCount>k__BackingField'
    static const int FIELD__FrameBufferCount = 20;

    //--//
};

struct Library_nanoFramework_Camera_nanoFramework_Camera_Camera
{
    static const int FIELD___configuration = 1;
    static const int FIELD___isInitialized = 2;

    NANOCLR_NATIVE_DECLARE(NativeInit___STATIC__I4__I4__I4__I4__I4__I4__I4__I4__I4__I4__I4__I4__I4__I4__I4__I4__I4__I4__I4__I4__I4);
    NANOCLR_NATIVE_DECLARE(NativeGetJpeg___STATIC__SZARRAY_U1);
    NANOCLR_NATIVE_DECLARE(NativeDeinit___STATIC__VOID);

    //--//
};

extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_nanoFramework_Camera;

#endif // NANOFRAMEWORK_CAMERA_H
